title: MLSA Workshop on Git/GitHub
theme: jekyll-theme-cayman
author: Abhinav Goyal
email : Abhinav.Goyal@studentambassadors.com
description: This is a GitHub Page to show the contribution of the attendees in MLSA workshop on "Introduction to Git and GitHub"
github_username: a-abhinav